### ISSUE TITLE
sed -i error with some versions of sed

### ISSUE THREAD

**Issue by markstur** [IBM/janusgraph-utils#35]
My sed (on a Mac) expects -i to be followed by an optional extension. So the current sed command fails like this:

Marks-MacBook-Pro:janusgraph-utils markstur$ sed -i '2s/.*/1,Indiana Jones/' /tmp/User.csv
sed: 1: "/tmp/User.csv": invalid command code U

It works w/ no extension by using the -e to terminate -i and start the expression. So I think this fix would be a more universal syntax (works on Mac):

sed -i -e '2s/.*/1,Indiana Jones/' /tmp/User.csv

If there are any issues w/ that, then I'd guess using > new-output-file instead of -i might be safest.

**Comment by chinhuang007** [comment]
Thanks for pointing it out. Interestingly the same sed command does not cause any errors in my colleague's mac. Anyway, I will add -e to be specific and safe. I like to update the file in-place so no additional files or steps are needed.
