### ISSUE TITLE
Problem about query to run!

### ISSUE THREAD

**Issue by StanYaha** [IBM/janusgraph-utils#56]
![image](https://user-images.githubusercontent.com/25735552/32046211-f66bfe5e-ba74-11e7-9cf4-e9d920ba860d.png)
The above code have sucessed!
![image](https://user-images.githubusercontent.com/25735552/32046271-26ac4664-ba75-11e7-8693-6b1bbdfcc240.png)
But this failed! I Have created the composite index with the property key id_number and successfully use the index in gremlin-shell.
Help me, thank you!

**Comment by chinhuang007** [comment]
Let's make sure the PropertyKey id_number is created properly. Can you get the schema checking tool from https://gist.github.com/robertdale/ad4c63910009dd1118abe67b33ce41e1, put the groovy file in your janusgraph/scripts, and run the following in gremlin console after you have connected to backends?

:load scripts/describe.groovy
:schema describe

If you see id_number is defined properly, run the exact gremlin query in the console first to verify it works. Then try it in curl.

**Comment by pluradj** [comment]
The problem is the quotes for the JSON payload are not escaped properly. This works:

```
curl -XPOST -Hcontent-type:application/json \
 -d '{"gremlin": "g.V().has(\"id_number\", \"450101195604161576\").toList()"}' \
 http://localhost:8182
```
