### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by dmoore247** [IBM/janusgraph-utils#63]
Excellent Readme!
I would additionally recommend specifying version(s) of JanusGraph, Gremlin, Java, Maven, git etc. that is required (or recommended) within the [README](https://github.com/IBM/janusgraph-utils/blob/master/README.md).

**Comment by chinhuang007** [comment]
Documented versions for JanusGraph, Java, Maven, and git. The Gremlin/TinkerPop version is associated with the JanusGraph version, https://github.com/JanusGraph/janusgraph/releases. Hope that provides sufficient version information.
