### ISSUE TITLE
how to use the vertex property (for example userid ) as the node_id  ?

### ISSUE THREAD

**Issue by zhaochl** [IBM/janusgraph-utils#69]
for example 

csv-conf/user.json

```json
{
  "VertexTypes": [
    {
      "name": "user",
      "columns": {
        "username": {"dataType":"String","composit":true},
        "userId": {"dataType":"Integer","composit":true}

      },
      "row": 100
    }
  ],
  "EdgeTypes": [
    {
      "name": "friends",
      "columns": {
        "friends-p1": {"dataType":"Long","composit":true}
      },
      "relations": [
        {"left": "user", "right": "user", "row": 1000 }
      ]
    }
  ]
}
```
then generator the follows:

user.csv|head -n10

```
node_id,username,userId
1,TlEOjVQlfP,82148167
2,sJkwhQNHnA,38310209
3,EdfxWvPErO,50166099
4,aTnbqEVCiT,76187948
5,nLTXRfrEGi,69962497
6,pKbhjVzllM,23196452
7,tkhdUUCopo,17549806
8,NoDEVxvqee,21428717
9,HYkUPStqkR,59599883
```
user_friends_user_edges.csv|head -n10

```
Left,Right,friends-p1
80,45,13808503
98,60,93985131
36,24,61345939
34,63,2160659
26,9,87308187
48,83,55073058
```

I want to user node_id as the user_id,so it's much more easy to update the node
thanks for any response!

**Comment by chinhuang007** [comment]
The generator currently creates a global property named "node_id" for all vertices and uses this unique property to generate edges. As a result, the user can simply specify the vertex types to define the edge relationships. Looks like the requested feature is to allow the users to specify the property names in addition to vertex types to define edges. The added flexibility requires new development.

**Comment by zhaochl** [comment]
OK thanks, I set node_id same equal with the userId as a trick, and it is useful ><:

**Comment by chinhuang007** [comment]
Since there is a solution, I am closing the issue.
