### ISSUE TITLE
error to batchImport data

### ISSUE THREAD

**Issue by JasonBian** [IBM/janusgraph-utils#79]
13:49:10 INFO  com.ibm.janusgraph.utils.importer.dataloader.DataFileLoader - Loading /Users/bianzexin/Downloads/tmp/Tweet.csv
13:49:10 INFO  com.ibm.janusgraph.utils.importer.vertex.VertexLoaderWorker - Starting new thread def5562c-bfa6-44fd-bdb1-b57e796e92fc
13:49:11 ERROR com.ibm.janusgraph.utils.importer.vertex.VertexLoaderWorker - Error in acceptRecord:: Vertex:: Tweet :: java.lang.NullPointerException
13:49:11 INFO  com.ibm.janusgraph.utils.importer.vertex.VertexLoaderWorker - acceptRecord::Vertex Removed
13:49:12 ERROR com.ibm.janusgraph.utils.importer.vertex.VertexLoaderWorker - Error in acceptRecord:: Vertex:: Tweet :: java.lang.NullPointerException
13:49:12 INFO  com.ibm.janusgraph.utils.importer.vertex.VertexLoaderWorker - acceptRecord::Vertex Removed
13:49:12 ERROR com.ibm.janusgraph.utils.importer.vertex.VertexLoaderWorker - Error in acceptRecord:: Vertex:: Tweet :: java.lang.NullPointerException
13:49:12 INFO  com.ibm.janusgraph.utils.importer.vertex.VertexLoaderWorker - acceptRecord::Vertex Removed

`if (!v.properties(propName).hasNext()) {
        			// TODO Convert properties between data types. e.g. Date
        			Object convertedValue = BatchHelper.convertPropertyValue(value,    							
        					graphTransaction.getPropertyKey(propName).dataType());
        			v.property(propName, convertedValue);
        		}`

graphTransaction.getPropertyKey(propName) return null

**Comment by JasonBian** [comment]
I have got the reason why raise this issue

**Comment by I-DO-NOT-KNOW** [comment]
> I have got the reason why raise this issue

Hello, I also met this issue, how did you solve this issue?
